function getCart(){return JSON.parse(localStorage.getItem("shopSphereCart")||"[]")}
function saveCart(cart){localStorage.setItem("shopSphereCart",JSON.stringify(cart)); updateCartCount()}
function money(n){return "₹"+n.toLocaleString("en-IN")}
function updateCartCount(){const el=document.getElementById("cartCount"); if(el) el.textContent=getCart().reduce((s,i)=>s+i.qty,0)}
function addToCart(id){const p=products.find(x=>x.id===Number(id)); if(!p)return; const c=getCart(); const item=c.find(x=>x.id===p.id); item?item.qty++:c.push({id:p.id,qty:1}); saveCart(c); alert(p.name+" added to cart!")}
function productCard(p){return `<div class="col-sm-6 col-lg-4"><div class="card product-card h-100 shadow-sm"><img src="${p.image}" class="card-img-top product-img" alt="${p.name}"><div class="card-body d-flex flex-column"><span class="badge category-badge align-self-start mb-2">${p.category}</span><h5>${p.name}</h5><p class="text-secondary small flex-grow-1">${p.description}</p><div class="d-flex justify-content-between align-items-center mb-3"><strong class="fs-5">${money(p.price)}</strong><span>⭐ ${p.rating}</span></div><div class="d-flex gap-2"><a href="product-details.html?id=${p.id}" class="btn btn-outline-dark flex-fill">Details</a><button class="btn btn-dark flex-fill" onclick="addToCart(${p.id})">Add to Cart</button></div></div></div></div>`}
function renderFeatured(){const el=document.getElementById("featuredProducts");if(el)el.innerHTML=products.slice(0,3).map(productCard).join("")}
function renderProducts(list=products){const el=document.getElementById("productGrid");if(el)el.innerHTML=list.length?list.map(productCard).join(""):`<div class="col-12"><div class="alert alert-warning">No products found.</div></div>`}
function initProducts(){if(!document.getElementById("productGrid"))return; renderProducts(); let cat="all"; document.querySelectorAll(".filter-btn").forEach(b=>b.onclick=()=>{cat=b.dataset.category;document.querySelectorAll(".filter-btn").forEach(x=>x.className="btn btn-outline-dark filter-btn");b.className="btn btn-dark filter-btn";filter()}); document.getElementById("searchInput").oninput=filter; function filter(){let q=document.getElementById("searchInput").value.toLowerCase();renderProducts(products.filter(p=>(cat==="all"||p.category===cat)&&(p.name.toLowerCase().includes(q)||p.description.toLowerCase().includes(q))))}}
function renderDetail(){const el=document.getElementById("productDetail");if(!el)return;const id=new URLSearchParams(location.search).get("id");const p=products.find(x=>x.id===Number(id))||products[0];el.innerHTML=`<div class="row g-5 align-items-center"><div class="col-md-6"><img src="${p.image}" class="img-fluid detail-img rounded-4 shadow-sm" alt="${p.name}"></div><div class="col-md-6"><span class="badge category-badge mb-2">${p.category}</span><h1 class="fw-bold">${p.name}</h1><div class="mb-3">⭐ ${p.rating} / 5</div><h2>${money(p.price)}</h2><p class="lead text-secondary">${p.description}</p><h5>Product Details</h5><ul>${p.details.map(x=>`<li>${x}</li>`).join("")}</ul><button class="btn btn-dark btn-lg" onclick="addToCart(${p.id})">Add to Cart</button> <a href="cart.html" class="btn btn-outline-dark btn-lg">View Cart</a></div></div>`}
function renderCart(){const el=document.getElementById("cartItems");if(!el)return;const c=getCart();if(!c.length){el.innerHTML='<div class="alert alert-info">Your cart is empty. <a href="products.html">Continue shopping</a>.</div>';document.getElementById("subtotal").textContent="₹0";document.getElementById("total").textContent="₹0";return}let sub=0;el.innerHTML=c.map(i=>{const p=products.find(x=>x.id===i.id);sub+=p.price*i.qty;return `<div class="card mb-3 shadow-sm"><div class="card-body d-flex align-items-center gap-3"><img src="${p.image}" class="cart-img" alt="${p.name}"><div class="flex-grow-1"><h5>${p.name}</h5><div>${money(p.price)}</div></div><div class="d-flex align-items-center gap-2"><button class="btn btn-sm btn-outline-dark" onclick="changeQty(${p.id},-1)">−</button><span>${i.qty}</span><button class="btn btn-sm btn-outline-dark" onclick="changeQty(${p.id},1)">+</button></div><button class="btn btn-sm btn-outline-danger" onclick="removeItem(${p.id})">Remove</button></div></div>`}).join("");document.getElementById("subtotal").textContent=money(sub);document.getElementById("total").textContent=money(sub+49)}
function changeQty(id,n){let c=getCart();let i=c.find(x=>x.id===id);if(i)i.qty+=n;c=c.filter(x=>x.qty>0);saveCart(c);renderCart()}
function removeItem(id){saveCart(getCart().filter(x=>x.id!==id));renderCart()}
document.addEventListener("DOMContentLoaded",()=>{updateCartCount();renderFeatured();initProducts();renderDetail();renderCart();const checkout=document.getElementById("checkoutBtn");if(checkout)checkout.onclick=()=>{if(!getCart().length){alert("Your cart is empty.");return}new bootstrap.Modal(document.getElementById("checkoutModal")).show()};const form=document.getElementById("checkoutForm");if(form)form.onsubmit=e=>{e.preventDefault();localStorage.removeItem("shopSphereCart");alert("Order placed successfully! This is a demo checkout.");location.href="index.html"};const cf=document.getElementById("contactForm");if(cf)cf.onsubmit=e=>{e.preventDefault();document.getElementById("contactMsg").innerHTML='<div class="alert alert-success">Thanks! Your message has been submitted.</div>';cf.reset()}});